name: Publish Docker Image

on:
  push:
    tags:
      - 'v*'  # Trigger cuando se crea un tag que comienza con "v"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker image
      run: |
        TAG=${GITHUB_REF##*/}
        echo "Building the Docker image with tag: $TAG"
        docker build -t your-dockerhub-username/your-repo-name:$TAG .

    - name: Push Docker image
      run: |
        TAG=${GITHUB_REF##*/}
        echo "Pushing the Docker image with tag: $TAG"
        docker push your-dockerhub-username/your-repo-name:$TAG
